### ISSUE TITLE
Initialize project structure

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/shelter_volunteers#10]
We need to pick the tech stack and initialize the repo with the project structure corresponding to that tech stack.

**Describe the solution you'd like**
The repo should be organized into directories, using the approach appropriate for the chosen tech stack. I think React JS client with a Flask (python) server side is a reasonable solution. @AbhilashKotha @loganwyas @Sai9797 What do you think on this?

**Comment by loganwyas** [comment]
Although I don't know React, I am very interested in learning it and believe that this will work for the project.

**Comment by kate-holdener** [comment]
Resolved with PR #11
