### ISSUE TITLE
Implement Shift Details and Volunteer Management in Shelter Dashboard

### ISSUE THREAD

**Issue by Brijitha1609** [oss-slu/shelter_volunteers#113]
**Is your feature request related to a problem? Please describe.**
Implement a component in the Shelter Dashboard to display complete details for each shift. Shelter staff need a way to view and manage specific details for shifts, including the ability to request more volunteers, close sign-ups, or delete a shift request.

**Describe the solution you'd like**
Implement functionality to display detailed information for each shift when the More Details button is clicked. This information should include:

1. Shift Start Time and Shift End Time
2. Requested Volunteers (total number of volunteers needed for the shift)
3. Signed Up Volunteers (number of volunteers currently signed up)
4. Required Volunteers (calculated as the difference between requested and signed-up volunteers)

In addition, include the following buttons for shift management:

- Request More Volunteers: Allows shelter staff to request additional volunteers if the signed-up volunteers are less than required.
- Close Sign-up of Volunteers: Stops further volunteer sign-ups for that specific shift.
- Close Request: Deletes or deactivates the shift request entirely.

The content for these above features needs to be implemented. Since the rest of the issue (styling) will be covered by https://github.com/oss-slu/shelter_volunteers/issues/120

The details should be displayed in a sidebar or modal, and clicking the More Details button should dynamically populate this section with information specific to the selected shift.

![image](https://github.com/user-attachments/assets/ac1923a8-6c1b-451a-9086-51879a8d415a)

**Comment by cbiddle3** [comment]
We are splitting this issue into 2 issues. It is too large for Amal's first time since she hasn't used React before and has minimal JavaScript experience. She hasn't done CSS styling either so this issue is being split into making the component with the required content, this next sprint she will implement the correct styling for the component.
