### ISSUE TITLE
Server-side: Include shelter information when listing upcoming and previous work shifts

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/shelter_volunteers#32]
**Is your feature request related to a problem? Please describe.**
When we list upcoming or previous workshifts, we only see the shelter id, without detailed information about this shelter (see screenshot below).
<img width="1566" alt="Screen Shot 2023-10-22 at 3 27 22 PM" src="https://github.com/oss-slu/shelter_volunteers/assets/42073871/053ff532-c4f7-4f7a-a5ac-ca911bea9e43">

Shelter id uniquely identifies each shelter within GetHelp platform. When we retrieve workshift information from our server side application, we also need to contact GetHelp API to retrieve more details about this shelter (location, any shelter specific requirements, etc) and pass that information in our response about the found workshifts. That information can later be presented to the user by the client side application.

**Additional context**
Details of the GetHelp API calls were shared in the project slack channel. Note that this issue is for server-side changes only, client side will be handled later separately.

**Comment by kate-holdener** [comment]
@Sai9797 this is a good issue for you to work on for sprint 4. It's server-side changes only. I am thinking you should add another use case to get_shelter_info, which will call GetHelp API and return information for a given shelter id. Then in the /list endpoint, you can add shelter information to the workshift json data. Let me know if you want to discuss. @AbhilashKotha had an example postman call to call GetHelp API to retrieve shelter data by id.

**Comment by AbhilashKotha** [comment]
<img width="1280" alt="image" src="https://github.com/oss-slu/shelter_volunteers/assets/113061137/1a1d84ce-f2c2-4038-9516-fc18784c652c">


Information that comes from API

{
            "id": 8955,
            "facilityType": "RECOVERY_RESIDENCE",
            "status": 0,
            "name": "Preferred Family Healthcare Inc",
            "organizationId": null,
            "phone": "(314) 889-0846",
            "website": null,
            "city": "Saint Louis",
            "state": "MO",
            "county": "Saint Louis City",
            "country": "usa",
            "zipCode": "63108",
            "latitude": 38.650953,
            "longitude": -90.25816,
            "privateAddress": false,
            "beds": 0,
            "baths": null,
            "favorite": null,
            "accreditations": [],
            "images": [],
            "distance": 0.0,
            "residentServed": "POP_UNDER_18,POP_18_65,POP_FEMALE_ONLY,POP_MALE_ONLY",
            "genderType": null,
            "acceptsInsurance": true,
            "avgCostMinimum": null,
            "depositAmount": null,
            "rentPaidWeekly": null,
            "moudMedications": null,
            "smokingPolicy": "PT_TOBACCO_ALLOWED_DESIGNATED",
            "bedUpdatedAt": null,
            "structureType": null,
            "volunteerNeeded": null,
            "volunteerCapacity": null,
            "volunteerCount": null
            }

**Comment by kate-holdener** [comment]
Is there a way to get shelter info by ID instead of postal code?

**Comment by AbhilashKotha** [comment]
Ex: https://api2-qa.gethelp.com/v2/facilities/8955
