### ISSUE TITLE
Include shelter information in upcoming and previous shifts pages

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/shelter_volunteers#43]
**Is this task related to a feature or a bug? Please include relevant issue numbers below.**
Once issue #32 is resolved, calls to /shifts endpoint returns shifts data with facility information. This facility information needs to be integrated into the client side application. Currently, the client side application shows only facility id for each shift.

**Describe the solution you'd like**
We can start by including the following information in the client side application (per shift):
name,
address
website
phone

**Additional context**
The facility_info field returned with each shift contains all the facility data we get from the GetHelp API, including the gps coordinates. Later, when we address issue #24 we can use this data to show shifts on the map.

**Comment by Pooja1672** [comment]
Hi @kate-holdener , I would like to work on this issue. Can you please assign it to me?

**Comment by kate-holdener** [comment]
@Pooja1672 , how's it going on this issue? Were you able to run the code in a dev environment and replicate the issue?

**Comment by kate-holdener** [comment]
@Pooja1672 Are you still planning to work on this issue? If not, we'll reassign it to someone else.
