### ISSUE TITLE
Add an option to cancel a work shift

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/shelter_volunteers#45]
**Is your feature request related to a problem? Please describe.**
We currently allow users to schedule volunteer work shifts, and see previous and upcoming work shifts. If a volunteer's plans change, they should be allowed to cancel their work shift. Our server side API has an endpoint supporting the delete operation on the work shift (DELETE /shifts/<SHIFT-ID>), but the client-side application does not expose this as a feature to the client. 

**Describe the solution you'd like**
In the upcoming shifts page of the client side application, provide a way to cancel each work shift. This only needs to happen for the upcoming shifts (past shifts cannot be cancelled). The user interface needs to be designed in a way that prevents users from accidentally canceling the work shift.

**Comment by jenniferlee20** [comment]
Hi! Could I be assigned this issue?

**Comment by kate-holdener** [comment]
@jenniferlee20 Sure, I'll assign it to you. Do you think you can get it done by November 20th?

**Comment by jenniferlee20** [comment]
Yes, I can definitely try. Thank you so much!

**Comment by kate-holdener** [comment]
Great! Let me know if you have any questions, and I'll be happy to answer.

**Comment by kate-holdener** [comment]
@jenniferlee20 are you still planning to work on this issue? If not, we can reassign it to someone else.

**Comment by jenniferlee20** [comment]
Hi, sorry for not keeping you updated. Yes I am! I recently finished and will soon create a pull request for the changes I have made.

**Comment by kate-holdener** [comment]
> Hi, sorry for not keeping you updated. Yes I am! I recently finished and will soon create a pull request for the changes I have made.

Thank you. You'll need to create a fork of our repository, commit your changes to that fork, and create a pull request from your fork to the main branch of our repo. Let me know if you have any questions.

**Comment by jenniferlee20** [comment]
Ok sounds good, thank you! I will let you know if I run into any issues as this will be my first time contributing to an open source project.

**Comment by jenniferlee20** [comment]
Just to make sure before I create the pull request, does this look right? 

<img width="1440" alt="merge confirmation" src="https://github.com/oss-slu/shelter_volunteers/assets/73796155/f1e70984-28e2-47f5-9be7-94cd4c15a631">

**Comment by kate-holdener** [comment]
@jenniferlee20 yes, that’s exactly where you want to be to create a pull request. Just continue down this path. GitHub user interface will guide you through the process.

**Comment by jenniferlee20** [comment]
Ok thank you, I just created the pull request! Please feel free to just look at the most recent commit and let me know if I can clarify anything.

**Comment by kate-holdener** [comment]
Resolved with PR #52
