### ISSUE TITLE
Disallow selecting times from the past

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/shelter_volunteers#48]
**Describe the bug**
Our current client-side application allows users to select the start and end time of their work shift, including times from the past (see screenshot below, where the selected time is from year 2022, while it's 2023 right now). The user interface should restrict time selection (start and end time) to only future times.
<img width="1404" alt="Screen Shot 2023-11-07 at 12 10 30 PM" src="https://github.com/oss-slu/shelter_volunteers/assets/42073871/7a867e11-6ac8-40fd-a3f6-6bf6ef26d926">

**To Reproduce**
Run the database, server side application, and the client side. Use the client side "Sign up for shifts" feature to sign up for a shift from the past time.

**Expected behavior**
Only future dates/times should be allowed as starting and ending time of a shift. Going back in time should be disabled.

**Comment by kate-holdener** [comment]
All yours @lirieh. Related to this, it would also be good to ensure that 'end time' cannot be before 'start time'. It would probably require similar code, so a judgement call if you want to fix it in this issue, or if we should track it separately.

**Comment by lirieh** [comment]
The existing code already had a fix to ensure that the 'end time' is always after the 'start time'. However, this is done by always changing the start time. For example, if the current start time is 3:00 pm and you try to change the end time to 2:00 pm, the system changes the start time to 2:00 pm and the end time becomes 3:00 pm. I think a better solution in this case could be to change the end time to 2:00 pm (as per the user request) and the start time to 1:00 pm. If it is ok with you I can change the logic to work like this before submitting my code.

**Comment by kate-holdener** [comment]
@lirieh let’s just not worry about the end time as compared to the start time for now (we can deal with it in a separate issue, as I think it deserves more discussion).
